### ISSUE TITLE
refactor ID handling

### ISSUE THREAD

**Issue by Benedikt1992** [CodeLionX/CommentSearchEngine#41]
Currently the handling of the different IDs (authorId, commentId, articleId) is very different between IDs. There is a extra handler, one handler was expanded to manage and one is managed outside of the pipeline.

Alls IDs can and should be managed in the same way. Either extra handler for each ID or use the `CommentWriter` to manage all IDs (last one is more efficient).

**Comment by SebastianSchmidl** [comment]
this was tackled in #48
