### ISSUE TITLE
Refactor vagrant build process

### ISSUE THREAD

**Issue by Benedikt1992** [CodeLionX/CommentSearchEngine#6]
also use seperate cse module for cse related provisioning

**Comment by Benedikt1992** [comment]
https://github.com/CodeLionX/CommentSearchEngine/blob/master/deployment/testing_environment/installProjectDeps.sh#L10 probably useless

**Comment by Benedikt1992** [comment]
Add more ressources to the box

**Comment by SebastianSchmidl** [comment]
fixed, see #25
